# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {D:/Vivado Doc/bt_uart.cache/wt} [current_project]
set_property parent.project_path {D:/Vivado Doc/bt_uart.xpr} [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {d:/Vivado Doc/bt_uart.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  {D:/Vivado Doc/bt_uart.srcs/sources_1/new/beep.v}
  {D:/Vivado Doc/bt_uart.srcs/sources_1/new/clk_div.v}
  {D:/Vivado Doc/bt_uart.srcs/sources_1/new/clk_gen.v}
  {D:/Vivado Doc/bt_uart.srcs/sources_1/new/cmd_parse.v}
  {D:/Vivado Doc/bt_uart.srcs/sources_1/new/debouncer.v}
  {D:/Vivado Doc/bt_uart.srcs/sources_1/new/lb_ctl.v}
  {D:/Vivado Doc/bt_uart.srcs/sources_1/new/meta_harden.v}
  {D:/Vivado Doc/bt_uart.srcs/sources_1/new/reset_bridge.v}
  {D:/Vivado Doc/bt_uart.srcs/sources_1/new/resp_gen.v}
  {D:/Vivado Doc/bt_uart.srcs/sources_1/new/rst_gen.v}
  {D:/Vivado Doc/bt_uart.srcs/sources_1/new/seg7decimal.v}
  {D:/Vivado Doc/bt_uart.srcs/sources_1/new/to_bcd.v}
  {D:/Vivado Doc/bt_uart.srcs/sources_1/new/uart_baud_gen.v}
  {D:/Vivado Doc/bt_uart.srcs/sources_1/new/uart_rx.v}
  {D:/Vivado Doc/bt_uart.srcs/sources_1/new/uart_rx_ctl.v}
  {D:/Vivado Doc/bt_uart.srcs/sources_1/new/uart_tx.v}
  {D:/Vivado Doc/bt_uart.srcs/sources_1/new/uart_tx_ctl.v}
  {D:/Vivado Doc/bt_uart.srcs/sources_1/new/bt_uart.v}
}
read_ip -quiet {{D:/Vivado Doc/bt_uart.srcs/sources_1/ip/clk_core/clk_core.xci}}
set_property used_in_implementation false [get_files -all {{d:/Vivado Doc/bt_uart.srcs/sources_1/ip/clk_core/clk_core_board.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Vivado Doc/bt_uart.srcs/sources_1/ip/clk_core/clk_core.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Vivado Doc/bt_uart.srcs/sources_1/ip/clk_core/clk_core_ooc.xdc}}]

read_ip -quiet {{D:/Vivado Doc/bt_uart.srcs/sources_1/ip/char_fifo/char_fifo.xci}}
set_property used_in_implementation false [get_files -all {{d:/Vivado Doc/bt_uart.srcs/sources_1/ip/char_fifo/char_fifo.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Vivado Doc/bt_uart.srcs/sources_1/ip/char_fifo/char_fifo_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Vivado Doc/bt_uart.srcs/sources_1/ip/char_fifo/char_fifo_ooc.xdc}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{D:/Vivado Doc/bt_uart.srcs/constrs_1/new/bt_uart_EGo.xdc}}
set_property used_in_implementation false [get_files {{D:/Vivado Doc/bt_uart.srcs/constrs_1/new/bt_uart_EGo.xdc}}]


synth_design -top bt_uart -part xc7a35tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef bt_uart.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file bt_uart_utilization_synth.rpt -pb bt_uart_utilization_synth.pb"
